#!/usr/bin/sh
echo "Build all"

cargo fmt --all
cargo update && cargo upgrade
cargo build && cargo build --release && cargo build --target=i686-pc-windows-msvc && cargo build --target=i686-pc-windows-msvc --release
